apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app8
  template:
    metadata:
      labels:
        app: php-app8
    spec:
      containers:
      - name: php-app8
        image: devopspk93/php-project
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: php-app8
spec:
  selector:
    app: php-app6
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
